"""Add Theme model

Revision ID: 25c9acdf6f4e
Revises: 7d81c6a617a2
Create Date: 2025-09-18 16:22:19.262471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25c9acdf6f4e'
down_revision = '7d81c6a617a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('complementary_color',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('complementary_color',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    op.drop_table('theme')
    # ### end Alembic commands ###
