"""Add complementary_color to Category

Revision ID: 7d81c6a617a2
Revises: 4e288743a110
Create Date: 2025-09-17 16:06:27.569791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d81c6a617a2'
down_revision = '4e288743a110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('complementary_color', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('complementary_color')

    # ### end Alembic commands ###
